update_interval = 250

layout = [
    ["weather", "weather", "weather", "weather", "weather", "weather"],
    ["weather", "weather", "weather", "weather", "weather", "weather"],
    ["latency", "latency", "latency", "status", "status", "status"]
]

[views.latency]
update_interval = 500 # 0.5 seconds
history_length = 25
target_host = "www.google.com"

[views.status]
update_interval = 10000 # 10 seconds

[views.weather]
update_interval = 600000 # 10 minutes
owm_language = "en"
owm_unit = "metric"